---
- name: EOS Playbook
  hosts: switches
  connection: local
  gather_facts: no

  tasks:

  - name: "Gather facts {{ inventory_hostname }}"
    eos_facts:
      gather_subset: all
    become: yes
    register: switch_facts

  - name: "Write switch_facts to a file"
    copy:
      content: "{{ switch_facts }}"
      dest: "{{ playbook_dir }}/output/{{ inventory_hostname }}.txt"
